apiVersion: v1
kind: Service
metadata:
  {{- with .Values.event_analysis_service.api }}

  name: {{ .service_name }}-service
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    svc: {{ .service_name }}
  ports:
    - name: {{ .service_name }}-service
      port: 80
      targetPort: {{ .port }}
      protocol: TCP
  type: ClusterIP

  {{- end }}
