data-analysis:
  event_analysis_service:
    db_name: "event-analysis"
    mongodb_readiness_connectivity_timeout: 2000
    api:
      replicas: 1
      service_name: "event-analysis-service-api"

      image: "ghcr.io/Fadude/event-analysis-service-api"
      version: {{ lookup("IMAGE_VERSION") }}
      requests_memory: "500Mi"
      requests_cpu: "0.5"
      limits_memory: "2000Mi"

      liveness: "/live"
      livenessInitialDelaySeconds: 15
      livenessTimeoutSeconds: 1

      readiness: "/ready"
      readinessInitialDelaySeconds: 15
      readinessTimeoutSeconds: 5

      flask_env: "production"
      log_level: "INFO"
      log_format: "%(levelname)s %(asctime)s - %(message)s"
      port: 4501

      openapi_path: "event_analysis_api/openapi/"
      openapi_file_name: "openapi.yaml"

      kafka_readiness_timeout: 5000
      kafka_env: "production"

      dependent_services: '{{ lookup("global.identity_service_endpoint") }}'
